//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orange_Skins_Project {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Readme : global::System.Configuration.ApplicationSettingsBase {
        
        private static Readme defaultInstance = ((Readme)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Readme())));
        
        public static Readme Default {
            get {
                return defaultInstance;
            }
        }
    }
}
